export const SERVER_URL = 'http://x-check.herokuapp.com';

export const REQUESTS_TABLE_TYPES = {
  PUBLISHED_REVIEWS: 'REVIEWS',
  DRAFTED_REQUESTS: 'DRAFTED_REQUESTS',
  PUBLISHED_REQUESTS: 'PUBLISHED_REQUESTS',
};

export const STATES = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
};
